for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Accelerated Sagittal IR-FSPGR\"" $i; done | sed 's|.json:    "SeriesDescription": "Accelerated Sagittal IR-FSPGR",||g' > Accelerated_Sagittal_IR-FSPGR.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"ORIG Anat T1w MP-RAGE 1mm (ABCD)\"" $i; done | sed 's|.json:    "SeriesDescription": "ORIG Anat T1w MP-RAGE 1mm (ABCD)",||g' > ORIG_Anat_T1w_MP-RAGE_1mm_ABCD.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Anat T1w MP-RAGE 1mm (ABCD)\"" $i; done | sed 's|.json:    "SeriesDescription": "Anat T1w MP-RAGE 1mm (ABCD)",||g' > Anat_T1w_MP-RAGE_1mm_ABCD.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"ORIG Sag_MPRAGE_T1\"" $i; done | sed 's|.json:    "SeriesDescription": "ORIG Sag_MPRAGE_T1",||g' > ORIG_Sag_MPRAGE_T1.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"PURE MP-RAGE 1mm\"" $i; done | sed 's|.json:    "SeriesDescription": "PURE MP-RAGE 1mm",||g' > PURE_MP-RAGE_1mm.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Ax T2 FLAIR\"" $i; done | sed 's|.json:    "SeriesDescription": "Ax T2 FLAIR",||g' > Ax_T2_FLAIR.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial T2 2D FLAIR\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial T2 2D FLAIR",||g' > Axial_T2_2D_FLAIR.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial T2 2D FLAIR ADNI2\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial T2 2D FLAIR ADNI2",||g' > Axial_T2_2D_FLAIR_ADNI2.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"ORIG Axial T2 2D FLAIR ADNI2\"" $i; done | sed 's|.json:    "SeriesDescription": "ORIG Axial T2 2D FLAIR ADNI2",||g' > ORIG_Axial_T2_2D_FLAIR_ADNI2.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"ADNI2 2D FLAIR\"" $i; done | sed 's|.json:    "SeriesDescription": "ADNI2 2D FLAIR",||g' > ADNI2_2D_FLAIR.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"ORIG ADNI2 2D FLAIR\"" $i; done | sed 's|.json:    "SeriesDescription": "ORIG ADNI2 2D FLAIR",||g' > ORIG_ADNI2_2D_FLAIR.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"ORIG Optional - Anat T2w CUBE FLAIR\"" $i; done | sed 's|.json:    "SeriesDescription": "ORIG Optional - Anat T2w CUBE FLAIR",||g' > ORIG_Optional_-_Anat_T2w_CUBE_FLAIR.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Optional - Anat T2w CUBE FLAIR\"" $i; done | sed 's|.json:    "SeriesDescription": "Optional - Anat T2w CUBE FLAIR",||g' > Optional_-_Anat_T2w_CUBE_FLAIR.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Optional - Sagittal 3D FLAIR\"" $i; done | sed 's|.json:    "SeriesDescription": "Optional - Sagittal 3D FLAIR",||g' > Optional_-_Sagittal_3D_FLAIR.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Sagittal 3D FLAIR\"" $i; done | sed 's|.json:    "SeriesDescription": "Sagittal 3D FLAIR",||g' > Sagittal_3D_FLAIR.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"ORIG Anat T2w CUBE (ABCD)\"" $i; done | sed 's|.json:    "SeriesDescription": "ORIG Anat T2w CUBE (ABCD)",||g' > ORIG_Anat_T2w_CUBE_ABCD.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Anat T2w CUBE (ABCD)\"" $i; done | sed 's|.json:    "SeriesDescription": "Anat T2w CUBE (ABCD)",||g' > Anat_T2w_CUBE_ABCD.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Sag_CUBE_T2\"" $i; done | sed 's|.json:    "SeriesDescription": "Sag_CUBE_T2",||g' > Sag_CUBE_T2.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial T2 Star\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial T2 Star",||g' > Axial_T2_Star.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial T2 Star (Rx 2D FLAIR)\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial T2 Star (Rx 2D FLAIR)",||g' > Axial_T2_Star_Rx_2D_FLAIR.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial 3D pCASL (Eyes Open)\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial 3D pCASL (Eyes Open)",||g' > Axial_3D_pCASL_Eyes_Open.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial 3D pCASL with Eyes Open\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial 3D pCASL with Eyes Open",||g' > Axial_3D_pCASL_with_Eyes_Open.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial DTI\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial DTI",||g' > Axial_DTI.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial DTI - swap pepolar CV\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial DTI - swap pepolar CV",||g' > Axial_DTI_-_swap_pepolar_CV.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial DTI 24vols flipped\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial DTI 24vols flipped",||g' > Axial_DTI_24vols_flipped.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial DTI 24dirs flipped\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial DTI 24dirs flipped",||g' > Axial_DTI_24dirs_flipped.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial DTI 24dir flipped\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial DTI 24dir flipped",||g' > Axial_DTI_24dir_flipped.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial DTI B=1000\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial DTI B=1000",||g' > Axial_DTI_B=1000.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial DTI B 1000\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial DTI B 1000",||g' > Axial_DTI_B_1000.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial DTI 24dirs flipped - RKV\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial DTI 24dirs flipped - RKV",||g' > Axial_DTI_24dirs_flipped_-_RKV.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial DTI B 1000 - RKV\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial DTI B 1000 - RKV",||g' > Axial_DTI_B_1000_-_RKV.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial rsfMRI (Eyes Open)\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial rsfMRI (Eyes Open)",||g' > Axial_rsfMRI_Eyes_Open.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial fMRI reverse blip\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial fMRI reverse blip",||g' > Axial_fMRI_reverse_blip.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial rsfMRI with Eyes Open - RKV\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial rsfMRI with Eyes Open - RKV",||g' > Axial_rsfMRI_with_Eyes_Open_-_RKV.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"Axial rsfMRI reverse blip - RKV\"" $i; done | sed 's|.json:    "SeriesDescription": "Axial rsfMRI reverse blip - RKV",||g' > Axial_rsfMRI_reverse_blip_-_RKV.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"B0 Map - DTI\"" $i; done | sed 's|.json:    "SeriesDescription": "B0 Map - DTI",||g' > B0_Map_-_DTI.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"B0 Map - DTI - RKV\"" $i; done | sed 's|.json:    "SeriesDescription": "B0 Map - DTI - RKV",||g' > B0_Map_-_DTI_-_RKV.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"B0 Map - rsfMRI\"" $i; done | sed 's|.json:    "SeriesDescription": "B0 Map - rsfMRI",||g' > B0_Map_-_rsfMRI.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"B0 Map - rsfMRI - RKV\"" $i; done | sed 's|.json:    "SeriesDescription": "B0 Map - rsfMRI - RKV",||g' > B0_Map_-_rsfMRI_-_RKV.txt
for i in `find . -name '*.json'`; do grep -wH "\"SeriesDescription\": \"HighResHippo\"" $i; done | sed 's|.json:    "SeriesDescription": "HighResHippo",||g' > HighResHippo.txt
